services:
  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: payment-service
    ports:
      - "8085:8085"
    expose:
      - "8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-payment:5432/marketplace
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2016
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
      - ORDER_SERVICE_URL=http://order-service:8084/api/orders
    depends_on:
      - postgres-payment
    develop:
      watch:
        - action: rebuild
          path: ./src/main/java
          ignore:
            - ./src/main/java/**/test/**
            - ./src/test/**
            - ./build/**
            - ./.gradle/**
        - action: rebuild
        - action: sync+restart
          path: ./src/main/resources
          target: /app/src/main/resources
        - action: sync
          path: ./build/libs/*.jar
          target: /app/app.jar
    networks:
      - backend

  postgres-payment:
    image: postgres:16-alpine
    container_name: postgres-payment
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2016
      POSTGRES_DB: marketplace
    volumes:
      - payment-pgdata:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    name: marketplace-backend

volumes:
  payment-pgdata: