spring.application.name=marketplace-payment-service
server.port=8085


spring.datasource.url=jdbc:postgresql://localhost:5432/marketplace
spring.datasource.username=postgres
spring.datasource.password=2016
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


order-service.url=http://localhost:8084/api/orders
resilience4j.circuitbreaker.instances.orderServiceCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.orderServiceCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.orderServiceCB.waitDurationInOpenState=10000

resilience4j.circuitbreaker.instances.notificationCB.slidingWindowSize=5
resilience4j.circuitbreaker.instances.notificationCB.failureRateThreshold=50
resilience4j.circuitbreaker.instances.notificationCB.waitDurationInOpenState=10000